apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vqplsc2i9-go
  janus-idp.io/tekton: vqplsc2i9-go
  backstage.io/kubernetes-id: vqplsc2i9-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vqplsc2i9-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
